Document: pythonhelloworld-debianpackage
Title: Debian pythonhelloworld-debianpackage Manual
Author: <insert document author here>
Abstract: This manual describes what pythonhelloworld-debianpackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pythonhelloworld-debianpackage/pythonhelloworld-debianpackage.sgml.gz

Format: postscript
Files: /usr/share/doc/pythonhelloworld-debianpackage/pythonhelloworld-debianpackage.ps.gz

Format: text
Files: /usr/share/doc/pythonhelloworld-debianpackage/pythonhelloworld-debianpackage.text.gz

Format: HTML
Index: /usr/share/doc/pythonhelloworld-debianpackage/html/index.html
Files: /usr/share/doc/pythonhelloworld-debianpackage/html/*.html
